# Generated by Django 5.1.3 on 2024-11-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="users",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="users",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="e_mail",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="username",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="wallet_address",
            field=models.CharField(blank=True, unique=True),
        ),
    ]
