# Generated by Django 5.1.3 on 2024-11-12 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Posts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("body", models.CharField(max_length=5000)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024,
                            11,
                            12,
                            14,
                            41,
                            55,
                            531081,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("like_count", models.IntegerField(blank=True)),
                ("dislike_count", models.IntegerField(blank=True)),
                ("reposts_count", models.IntegerField(blank=True)),
            ],
        ),
    ]
