# Generated by Django 5.1.3 on 2024-11-12 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 11, 12, 15, 35, 41, 374563, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="posts",
            name="dislike_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="posts",
            name="like_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="posts",
            name="reposts_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
